# Generated by Django 2.1.4 on 2019-03-01 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20190227_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3file',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
